---
name: mongo-sinatra-books
root: ~/optimiz/mongo-sinatra-books
pre_window: >
  promote ~/optimiz/mongo-sinatra-books/.env.development &&
  rbenv global 2.7.6
windows:
  - mns_doc:
      layout: main-vertical
      panes:
        - org_mns:
            - nvim +e ~/Documents/mns.dotoo
        - dbg_mns:
            - rbenv exec bundle exec pry -I . --exec 'load "lib/server.rb"'
  - mns_app:
      - overmind connect -s ~/optimiz/mongo-sinatra-books/tmp/dev.sock mns_app
      # (n/w: - overmind -s "0.0.0.0:4321" -S "tcp" mns_app)
  - wrk:
      layout: main-vertical
      panes:
        - edt_mns:
            - nvim +NERDTreeToggle +NERDTreeVCS
        - tdd_mns:
            - bundle exec env RACK_ENV=test guard
